name: FWium-lite CI

on: [ push ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: maven:3.8.1-jdk-11
    env:
      HUB_HOST: hub
      HUB_PORT: 4444
      THREAD_COUNT: 2
    services:
      hub:
        image: selenium/hub:4.0.0-beta-3-20210426
        ports:
          - 4442-4444:4442-4444
      chrome1:
        image: selenium/node-chrome:4.0.0-beta-3-20210426
        options: -v /dev/shm:/dev/shm
        env:
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
          SE_EVENT_BUS_HOST: hub
      chrome2:
        image: selenium/node-chrome:4.0.0-beta-3-20210426
        options: -v /dev/shm:/dev/shm
        env:
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
          SE_EVENT_BUS_HOST: hub
      firefox1:
        image: selenium/node-firefox:4.0.0-beta-3-20210426
        options: -v /dev/shm:/dev/shm
        env:
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
          SE_EVENT_BUS_HOST: hub
      firefox2:
        image: selenium/node-firefox:4.0.0-beta-3-20210426
        options: -v /dev/shm:/dev/shm
        env:
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
          SE_EVENT_BUS_HOST: hub
    steps:
      - uses: actions/checkout@v2
#      - name: Setup JDK 11
#        uses: actions/setup-java@v2
#        with:
#          java-version: '11'
#          distribution: 'adopt'
      - name: Cache Maven deps
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      #      # Set up code climate test reporter
      #      - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      #      - chmod +x ./cc-test-reporter
      #      - ./cc-test-reporter before-build
      - name: Compile and run checkstyle
        run: |
          mvn test-compile \
            --batch-mode --show-version \
            -DskipTests=true -Dmaven.javadoc.skip=true
      - name: test grid
        run: curl -L http://${HUB_HOST}:4444/status
      - name: Run tests against Chrome grid
        run: |
          mvn verify --batch-mode \
            -Dthreads=${THREAD_COUNT} \
            -Dbrowser=chrome \
            -Dheadless \
            -DreuseBrowser \
            -DgridURL=http://${HUB_HOST}:4444/
      - name: Run tests against Firefox grid
        run: |
          mvn verify --batch-mode \
            -Dthreads=${THREAD_COUNT} \
            -Dbrowser=firefox \
            -Dheadless \
            -DreuseBrowser \
            -DgridURL=http://${HUB_HOST}:4444/
      - name: Install chrome and chromedriver locally
        run: |
          wget --quiet https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          apt install ./google-chrome-stable_current_amd64.deb
          wget --quiet http://chromedriver.storage.googleapis.com/90.0.4430.24/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
      - name: Run tests against local Chrome
        run: |
          mvn verify --batch-mode \
            -Dthreads=${THREAD_COUNT} \
            -Dbrowser=chrome \
            -Dheadless \
            -DreuseBrowser
      - name: Install Firefox and Gecko Driver
        run: |
          apt update && apt install -y firefox
          export GECKO_VER=0.29.1
          wget --quiet https://github.com/mozilla/geckodriver/releases/download/v${GECKO_VER}/geckodriver-v${GECKO_VER}-linux64.tar.gz
          tar -xzf geckodriver-v${GECKO_VER}-linux64.tar.gz
      - name: Use custom Firefox browser impl
        run: |
          mvn verify --batch-mode \
            -DcustomBrowserImpl=com.frameworkium.integration.CustomFirefoxImpl \
            -Dheadless \
            -Dmaximise=true \
            -Dit.test=DocumentationTest
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: fwium-logs
          path: logs/
          retention-days: 7
